language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t yishayf/docker-react -f Dockerfile.dev .

script:
  - docker run yishayf/docker-react npm run test -- --coverage
