language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t yishayweb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yishayweb/docker-react npm run test
